#!/usr/bin/env python3

"""Print foreign exchange market rate declared by the Czech National Bank.

Format of the foreign exchange market rates:
https://www.cnb.cz/en/faq/Format-of-the-foreign-exchange-market-rates/

Further details:
https://www.cnb.cz/en/financial-markets/foreign-exchange-market/central-bank-exchange-rate-fixing/central-bank-exchange-rate-fixing/

TODO:
    * Emit warning: Foreign exchange market rates as of a given date are
      updated only once a day (every working day after 2.30 p.m.).
"""

import argparse
import os
import sys
import textwrap
import urllib.request
from datetime import date


def get_fx_rates(url):
    """Return FX rates from URL as dict.

    Supports only the format provided by the Czech National Bank.

    Returns: dict(currency_code: str, fx_rate: str)
    """
    with urllib.request.urlopen(url) as response:
        data = response.read().decode("utf-8")  # FIXME: don't guess the data encoding

    fx_rates = dict()
    for line in data.split("\n")[2:]:  # skip ID and header lines
        fields = line.split("|")
        if line == "":
            # If data ends with newline, the last line is empty.
            continue
        fx_rates[fields[-2]] = fields[-1]

    return fx_rates


def main():
    """Script entry point"""

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """\
            environment variables:
              FXRATES_URL custom url to a file containing FX rates, e.g. file:///path/to/daily.txt
        """
        ),
    )

    parser.add_argument("currency", help="currency ISO code, e.g. USD")
    parser.add_argument(
        "date",
        nargs="?",
        help="optional date in ISO format, e.g. 2022-01-01; default: today",
    )
    args = parser.parse_args()

    valid_currencies = [
        "AUD",
        "BGN",
        "BRL",
        "CAD",
        "CHF",
        "CNY",
        "DKK",
        "EUR",
        "GBP",
        "HKD",
        "HRK",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "ISK",
        "JPY",
        "KRW",
        "MXN",
        "MYR",
        "NOK",
        "NZD",
        "PHP",
        "PLN",
        "RON",
        "RUB",
        "SEK",
        "SGD",
        "THB",
        "TRY",
        "USD",
        "XDR",
        "ZAR",
    ]
    custom_url = os.getenv("FXRATES_URL")
    if custom_url:
        file_url = custom_url
    else:
        file_url = "https://www.cnb.cz/en/financial-markets/foreign-exchange-market/central-bank-exchange-rate-fixing/central-bank-exchange-rate-fixing/daily.txt"
    if args.date:
        # add URL query '?date=DD.MM.YYYY'
        file_url += f"?date={date.fromisoformat(args.date).strftime('%d.%m.%Y')}"

    if args.currency not in valid_currencies:
        print(
            f"error: invalid currency code; valid codes: {' '.join(valid_currencies)}",
            file=sys.stderr,
        )
        sys.exit(1)

    fx_rates = get_fx_rates(file_url)
    print(fx_rates[args.currency])


if __name__ == "__main__":
    main()
