#!/usr/bin/env bash
#
# Make a backup of $HOME dir.
#
# Simply syncs content of $HOME dir with its destination dir via rsync.
#
# NOTE:
#   Using $USER or $HOSTNAME for determining backup dir is wrong design as it
#   may lead to unexpected behavior - user or hostname may change unexpectedly
#   for some environments (e.g. toolbox).

set -o errexit
set -o nounset

src="${HOME}"
dest="/run/media/petr/backup/hydrogen"

rsync \
    --verbose \
    --archive \
    --human-readable \
    --exclude-from="${HOME}/.rbak/exclude" \
    --delete \
    --delete-excluded \
    "${src}" \
    "${dest}/home"
