#!/bin/bash
#
# Notify me when the pending rpm-ostree deployment contains security advisories.
#
# Optionally, the script may initiate immediate system upgrade.
#
# usage:
#   rpm-ostree-notify --frequency '30m' --start-delay '10s' --do-upgrade
#

source "$(dirname "${0}")/rpm-ostree-notify.conf"

help_msg="\
usage:
  ${0} [OPTIONS...]

options:
  -h, --help        show this help and exit
  --frequency=FREQ  FREQ determines how often to show a notification,
                    e.g. every '30s', '30m', '1h'
  --start-delay=DELAY   how long should this program wait until it starts
                    checking for pending security advisories, e.g. '10s',
                    '5m'
  --do-upgrade      do immediate upgrade once a new deployment with security
                    advisories is available
"

#
# parse args
#
# For details see http://mywiki.wooledge.org/BashFAQ/035
#

# Make sure no unexpected vals are taken from the environment.
frequency=
start_delay=
do_upgrade=

while true; do
    case ${1} in
        -\?|-h|--help)
            echo "${help_msg}"
            exit
            ;;
        --frequency)
            if [[ "${2}" ]]; then
                frequency=${2}
            else
                echo "--frequency requires some frequency, e.g. '30m'" >&2
                exit 1
            fi
            ;;
        --frequency=?*)
            frequency=${1#*=}
            ;;
        --frequency=)
            echo "--frequency requires some frequency, e.g. '30m'" >&2
            exit 1
            ;;
        # FIXME
    esac
done

echo "${frequency}"
exit 2

sleep "${START_DELAY}"  # Let rpm-ostree download latest updates

while true; do
    sec_advisories=$(rpm-ostree status | grep 'SecAdvisories')
    if [[ ${sec_advisories} ]]; then
        if [[ ${IMMEDIATE_UPGRADE} ]]; then
            rpm-ostree upgrade
            msg_end='Consider to reboot the system.'
        else
            msg_end='Consider to manually upgrade and reboot the system.'
        fi
        msg_summary='Security Advisories Available'
        msg_start='Pending rpm-ostree deployment contains security advisories:'
        adv_list=$(echo "${sec_advisories}" | cut -d':' -f2)
        # Use urgency critical to ensure I won't overlook the notification
        notify-send --urgency=critical "${msg_summary}" "${msg_start} ${adv_list}. ${msg_end}"
    fi
    sleep "${FREQUENCY}"
done
