#!/bin/python3
"""Print a random message of the day to stdout."""
# ruff: noqa: T201
from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path


def main() -> int:  # noqa: D103
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "file",
        type=Path,
        help=(
            "path to a file with messages of the day (1 message per line,"
            " empty lines are ignored)"
        ),
    )
    args = parser.parse_args()

    try:
        with args.file.open("r") as f:
            messages = [line.strip() for line in f.readlines() if line.strip()]
    except OSError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    print(random.choice(messages))  # noqa: S311

    return 0


if __name__ == "__main__":
    sys.exit(main())
